-- Optional seed (run after migration). Adjust bucket URLs after uploading to Storage.

insert into public.templates (
  slug,
  title,
  short_description,
  full_description,
  category,
  platforms,
  price,
  sale_price,
  featured_image,
  gallery_images,
  live_demo_url,
  preview_video_url,
  features,
  tech_stack,
  included_pages,
  seo_score,
  speed_score,
  mobile_score,
  conversion_score,
  rating,
  review_count,
  is_featured,
  published
) values (
  'cms-seed-store',
  'CMS Seed Store',
  'Reference row created from SQL — replace with your assets in the admin panel.',
  'This template was inserted via seed.sql. Use the Next.js admin at /admin/templates to edit or add storefronts. Images can be stored in the `template-images` Supabase bucket.',
  'Storefront',
  '["Shopify","Shopify Plus"]'::jsonb,
  79.00,
  59.00,
  'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80',
  '["https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80"]'::jsonb,
  '/#demo',
  '',
  '[
    {"title":"SEO optimized","description":"JSON-LD and section-level meta."},
    {"title":"High conversion","description":"Merchandising blocks and proof bands."}
  ]'::jsonb,
  '["Shopify OS 2.0","Liquid","JSON templates"]'::jsonb,
  '["Home","Product","Collection","Cart","Blog"]'::jsonb,
  99,
  98,
  99,
  97,
  4.9,
  200,
  true,
  true
) on conflict (slug) do nothing;
